critics = {'Lisa Rose' : {'Lady in the Water' : 2.5,
                          'Snakes on a Plane' : 3.5,
                          'Just My Luck' : 3.0,
                          'Supermen Returns' : 3.5,
                          'You, Me and Dupree' : 2.5,
                          'The Night Listener' : 3.0
                          },
           'Gene Seymour' : {'Lady in the Water' : 3.0,
                          'Snakes on a Plane' : 3.5,
                          'Just My Luck' : 1.5,
                          'Supermen Returns' : 5.,
                          'You, Me and Dupree' : 3.5,
                          'The Night Listener' : 3.0
                          },
           'Michael Phillips' : {'Lady in the Water' : 2.5,
                          'Snakes on a Plane' : 3.,
                          'Supermen Returns' : 3.5,
                          'The Night Listener' : 4.0
                          },
           'Claudia Puig': { 'Snakes on a Plane': 3.5,
                         'Just My Luck': 3.0,
                         'Supermen Returns': 4.,
                         'You, Me and Dupree': 2.5,
                         'The Night Listener': 4.5
                         },
           'Mick LaSalle': {'Lady in the Water': 3.,
                         'Snakes on a Plane': 4.,
                         'Just My Luck': 2.0,
                         'Supermen Returns': 3.,
                         'You, Me and Dupree': 2.0,
                         'The Night Listener': 3.0
                         },
           'Jack Matthews': {'Lady in the Water': 3.,
                         'Snakes on a Plane': 4.,
                         'Just My Luck': 3.0,
                         'Supermen Returns': 5,
                         'You, Me and Dupree': 3.5,
                         'The Night Listener': 3.0
                         },
           'Toby': {'Snakes on a Plane': 4.5,
                         'Supermen Returns': 4.,
                         'You, Me and Dupree': 1.0,
                         },

           }